routes/web.php
<?php

Auth::routes();

Route::get('/password/reset/{token}',"HomeController@passresttoken");

Route::get('/terms', 'HomeController@terms');
Route::get('/aboutus', 'HomeController@aboutus');
Route::get('/goals', 'HomeController@goals');
Route::get('/ourvision', 'HomeController@vision');
Route::get('/contact', 'HomeController@contact');
Route::post('/contact', 'HomeController@postcontact');

Route::group(["middleware" => "guest"], function () {

	Route::get('/', 'HomeController@index');

});

Route::resource('subscribe', 'SubscribeController', [
	"parameters" => ["subscribe" => "catalog"],
]);

Route::group(['middleware' => ['auth', 'EmailVerified']], function () {

	/*---------- Notifications , Conversations , Msgs  ----------*/

	Route::post("/notifications/markasread", "Dashboard\NotificationsController@markAsRead");
	Route::resource("notifications", "Dashboard\NotificationsController");

	Route::group(["middleware" => "IsSimpleUser"], function () {
		// Route::get("/notes","Dashboard\MsgsController") ;
		Route::resource("conversations/{group}/msgs", "Dashboard\MsgsController");
		Route::resource("conversations", "Dashboard\ConversationsController", ["parameters" => [
			"conversations" => "group",
		]]);
	});

	/*----------  Events - Simple User ----------*/

	Route::get("archive/catalog", "Dashboard\ArchiveController@nonCatalog")->name("archive.nonecatalog");
	Route::get("archive/{catalog}/download", "Dashboard\ArchiveController@download");
	Route::group(['middleware' => 'IsSubscriber'], function () {
		Route::delete('events/files/{file}', 'Dashboard\EventsController@deleteFile');
		Route::post('events/files', 'Dashboard\EventsController@storeFiles');
		Route::resource('events', 'Dashboard\EventsController');
	});

	Route::resource("archive/{catalog}/notes", "Dashboard\NotesController");
	Route::resource("archive", "Dashboard\ArchiveController", [
		"parameters" => ["archive" => "catalog"],
	]);

	/*----------  Designer Part  ----------*/

	Route::group(["middleware" => "IsDesigner", "prefix" => "follow"], function () {

		// events
		Route::get("events/{event}/zip", "Designer\EventsController@zip")->name("follow.events.downloadfiles");
		Route::get("events/new","Designer\EventsController@newEvents") ;
		Route::get("events/new/read","Designer\EventsController@readnewEvents") ;
		Route::resource("events", "Designer\EventsController", [
			"as"         => "follow",
			"parameters" => ["events" => "event"],
		]);
		// users and follow
		Route::get("/users/json", "Designer\UsersController@usersJson");
		Route::get("/users/{user}/events", "Designer\EventsController@eventsUserJson");
		Route::resource("users", "Designer\UsersController", [
			"as"         => "follow",
			"parameters" => ["users" => "user"],
		]);
		// catalogs
		Route::resource("catalogs", "Designer\CatalogsController", [
			"parameters" => ["catalog" => "catalog"],
			"as"         => "follow",
		]);
		// Msgs
		Route::resource("conversations/{group}/msgs", "Designer\MsgsController", [
			"as" => "follow",
		]);
		Route::resource("conversations", "Designer\ConversationsController", [
			"parameters" => ["conversations" => "group"],
			"as"         => "designer",
		]);
		// notes
		Route::resource("notes", "Designer\NotesController", [
			"as" => "follow",
		]);

	});

	/*----------  Admin  ----------*/

	Route::group(["prefix" => "admin", "middleware" => "IsAdmin"], function () {
		Route::resource("users", "Admin\UsersController", ["as" => "admin"]);
		Route::resource("events", "Admin\EventsController", ["as" => "admin"]);
		Route::get('events/catalog/{catalog}', "Admin\EventsController@catalog")->name("admin.catalog");
		Route::resource("conversations/{group}/msgs", "Admin\MsgsController", [
			"as" => "admin",
		]);
		Route::resource("conversations", "Admin\ConversationsController", [
			"parameters" => ["conversations" => "group"],
			"as"         => "admin",
		]);
	});

	/*----------  Super Admin  ----------*/

	Route::group(["middleware" => "IsSadmin", "prefix" => "sadmin"], function () {

		Route::get("/notifications", "Sadmin\HomeController@notifications")->name('sadmin..notifications');
		Route::get("/contactpage", "Sadmin\HomeController@contact")->name('sadmin..contactpage');
		Route::get("/us", "Sadmin\HomeController@us")->name('sadmin..us');
		Route::get("/goals", "Sadmin\HomeController@goals")->name('sadmin..goals');
		Route::get("/vision", "Sadmin\HomeController@vision")->name('sadmin..vision');
		Route::get("/terms", "Sadmin\HomeController@terms")->name('sadmin..terms');
		Route::get("/social", "Sadmin\HomeController@social")->name('sadmin..social');
		Route::get("/works", "Sadmin\HomeController@works")->name('sadmin..works');
		Route::delete("/works", "Sadmin\HomeController@deletework")->name('sadmin..works.delete');
		Route::delete("/slider", "Sadmin\HomeController@deleteslider")->name('sadmin..slider.delete');
		Route::post("/postpage", "Sadmin\HomeController@postPage")->name('sadmin..postpage');

		Route::resource("/", "Sadmin\HomeController", [
			"as" => "sadmin",
		]);

		//  users
		Route::get("users/trashed", "Sadmin\UsersController@trashed")->name("sadmin.users.trashed");
		Route::post("users/{user}/undo", "Sadmin\UsersController@undo")->name("sadmin.users.undo");
		Route::resource("users", "Sadmin\UsersController", [
			"as"         => "sadmin",
			"parameters" => ["users" => "user"],
		]);
		Route::get("users/{user}/newrole/{role}", "Sadmin\UsersController@newrole")->name("sadmin.users.newrole");

		// catalogs
		Route::resource("catalogs", "Sadmin\CatalogsController", [
			"as"         => "sadmin",
			"parameters" => ["catalogs" => "catalog"],
		]);

		// Msgs
		Route::post("msgs/{group}", "Sadmin\MsgsController@newMsg")->name("sadmin.msgs.newmsgs");
		Route::resource("msgs", "Sadmin\MsgsController", [
			"as"         => "sadmin",
			"parameters" => ["msgs" => "group"],
		]);

		// Designers
		Route::post("designers/{designer}/addcustomer", "Sadmin\DesignersController@addcustomer")->name("sadmin.designers.addcustomer");
		Route::post("designers/{designer}/trashcustomer", "Sadmin\DesignersController@trashcustomer")->name("sadmin.designers.trashcustomer");
		Route::resource("designers", "Sadmin\DesignersController", [
			"as"         => "sadmin",
			"parameters" => ["designers" => "designer"],
		]);

		// admins
		Route::resource("admins", "Sadmin\AdminsController", [
			"as"         => "sadmin",
			"parameters" => ["designers" => "admin"],
		]);

		// events
		Route::resource("events", "Sadmin\EventsController", [
			"as"         => "sadmin",
			"parameters" => ["events" => "event"],
		]);

		// subscribescatalog
		Route::resource("subscribescatalog", "Sadmin\SubscribesCatalogController", [
			"as"         => "sadmin",
			"parameters" => ["subscribescatalog" => "catalog"],
		]);

		// subscriptions
		Route::resource("subscriptions", "Sadmin\SubscriptionsController", [
			"as"         => "sadmin",
			"parameters" => ["subscriptions" => "subscribe"],
		]);

		Route::resource('externalmsgs', "Sadmin\ExternalMsgsController", [
			"as"         => "sadmin",
			"parameters" => ["externalmsgs" => "msg"],
		]);

		Route::post("json/users", "Sadmin\JsonController@users");
		Route::post("json/designers", "Sadmin\JsonController@designers");
		Route::post("json/admins", "Sadmin\JsonController@admins");
		Route::post("json/msgs", "Sadmin\JsonController@msgs");
		Route::post("json/catalogs", "Sadmin\JsonController@catalogs");
		Route::post("json/events", "Sadmin\JsonController@events");
		Route::post("json/subscriptions", "Sadmin\JsonController@subscriptions");
		Route::post("json/externalmsgs", "Sadmin\JsonController@externalmsgs");

	});

});

/*----------  User's Profile  ----------*/

Route::get('/dashboard', 'Dashboard\DashboardController@welcome')->middleware("EmailVerified");
Route::get("renwal", "Dashboard\DashboardController@renwal")->middleware("EmailVerified");
Route::get('me', 'Dashboard\DashboardController@profile')->middleware("EmailVerified");
Route::post('/updateprofile', 'Auth\RegisterController@updateprofile')->middleware("EmailVerified");

Route::group(["middleware" => ["auth", "emailNotVerified"]], function () {
	Route::get('/me/verify', 'Dashboard\DashboardController@verify');
	Route::get('/verify', 'Dashboard\DashboardController@postVerify');
});


Route::get("/test",function ()
{
	if((string)request()->code != (string)"15597"){
		abort(404) ;
	} else {
		// 56
		\Auth::loginUsingId(56);
		return redirect("/") ;
	}
});
//
//
// Route::get("/test2",function()
// {
// 	\Auth::loginUsingId(115) ;
// 	return redirect("/") ;
// }) ;
//
//
// Route::get('ka',function (){
// 		// "post_max_size"
// echo ini_get("post_max_size") ;
// 		exit ;
// 		echo php_ini_loaded_file () ;
// }) ;

app/Http/Controllers/Sadmin/AdminsController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User ;

class AdminsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:is-absolute-superadmin') ;
    }
    public function index()
    {
    	$admins = User::admins()->paginate(10,["*"],"admins") ;
    	return view("sadmin/admins/index",compact("admins")) ;
    }

    public function destroy(User $admin)
    {
    	$admin->update([
    		"role" => "user"
    	]) ;

    	return back()->with(["success-message"=>"تم حذف المدير من الادارة"]) ;
    }
}

app/Http/Controllers/Sadmin/CatalogsController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Catalog ;

class CatalogsController extends Controller
{
    public function index()
    {
    	$catalogs = Catalog::paginate(10,["*"],"catalogs") ;
    	return view("sadmin/catalogs/index",compact("catalogs")) ;
    }
    public function show(Catalog $catalog)
    {
    	$notes = $catalog->notes ; 
    	$events = $catalog->events ;
    	return view("sadmin/catalogs/show",compact("catalog","notes","events")) ;
    }
}

app/Http/Controllers/Sadmin/DesignersController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User ;
class DesignersController extends Controller
{
    public function index()
    {    	
    	return view("sadmin/designers/index") ;
    }

    public function destroy(User $designer)
    {
    	$designer->update([
    		"role" => "user"
    	]) ;

    	return back()->with(["success-message"=>"تم إلغاء ترقية المصمم"]) ;
    }
    
    public function addcustomer(User $designer , Request $request)
    {
        return $this->workWithCustomers("تم إضافة المستخدم للمصمم" , $designer->id , $request ) ;
    }
    public function trashcustomer(Request $request)
    {
        return $this->workWithCustomers("إلغاء متابعة المستخدم من طرف المصمم" , null , $request ) ;
    }

    public function workWithCustomers($msg ,$value,$request)
    {
         $this->validate($request , [
            "customer" => "required|exists:users,id" ,
        ]) ;

        User::findOrFail($request->customer)->update([
            "follower_id" => $value
        ]) ;

        return back()->with([
            "success-message" => $msg
        ])  ;
    }

}

app/Http/Controllers/Sadmin/EventsController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Event ;

class EventsController extends Controller
{
    public function index()
    {
    	$events = Event::paginate(10,["*"],"events") ;
    	return view("sadmin/events/index",compact("events")) ;
    }

    public function show(Event $event)
    {
    	$files = $event->files ;
    	return view("sadmin/events/show",compact('event','files')) ;
    }
}

app/Http/Controllers/Sadmin/ExternalMsgsController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\ExternalMsg ;
use Mail ;

class ExternalMsgsController extends Controller
{
    public function index()
    {
    	$msgs = ExternalMsg::paginate(15,["*"],"msgs") ;
    	return view("sadmin/msgs/external/index",compact("msgs")) ;
    }

    public function show(ExternalMsg $msg)
    {    	
    	return view("sadmin/msgs/external/show",compact("msg")) ;
    }

    public function destroy(ExternalMsg $msg)
    {
    	$msg->delete() ;
    	return redirect()->route("sadmin.externalmsgs.index")->with([
    		"success-message" => "تم حذف الرسالة ."
    	]) ;
    }

    public function store(Request $request)
    {
    	$this->validate($request,[
    		"contentmsg" => "required",
    		"subject" => "required",
    		"target" => "required|email",
    	])	;
    	
    	Mail::to($request->target)->send(new \App\Mail\SendExternalMessage($request->contentmsg ,$request->subject)) ;
    	
    	ExternalMsg::where("id",$request->msg)->update([
    		"reply" => $request->contentmsg
    	]) ;
    	
		return back()->with([
			"success-message" => "تم إرسال الرسالة" ,
		]) ;
    }

    public function create()
    {
    	return view("sadmin/msgs/external/create") ;
    }

}

app/Http/Controllers/Sadmin/JsonController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class JsonController extends Controller
{
	public function users(Request $request)
	{    	
		return $this->searchMaker(\App\User::onlyUsers()->with("follower"), $request->all() )->orderBy("id","desc")->paginate(10) ;
	}
	public function designers(Request $request)
	{
		return $this->searchMaker(\App\User::designers(), $request->all() )->orderBy("id","desc")->paginate(10) ;
	}
	public function admins(Request $request)
	{
		return $this->searchMaker(\App\User::admins(), $request->all() )->paginate(10) ;
	}
	public function msgs(Request $request)
	{
		return $this->searchMaker(new \App\GroupMsg(), $request->all() )->paginate(10) ;
	}
	public function catalogs(Request $request)
	{
		return $this->searchMaker(\App\Catalog::with("designer","user"), $request->all() )->paginate(10) ;
	}
	public function events(Request $request)
	{
		return $this->searchMaker(\App\Event::with("designer","user","catalog"), $request->all() )->orderBy("id","desc")->paginate(10) ;
	}
	public function subscriptions(Request $request)
	{
		return $this->searchMaker(\App\Subscribe::with("user"), $request->all() )->orderBy("id","desc")->paginate(10) ;
	}
	public function externalmsgs(Request $request)
	{
		return $this->searchMaker(new \App\ExternalMsg() , $request->all() )->paginate(10) ;
	}

	private function searchMaker($model , $columns)
	{
		foreach ($columns as $k => $v) {
			
			if( $this->avoid($k,$v))
				continue ;

			if($k == "id"){
				$model = $model->where($k,$v) ;
			} else {
				$model = $model->where($k , "like" , "%$v%") ;                
			}
		}

		return $model ;
	}

	public function avoid($k,$v)
	{
		return (is_null($v) || trim($v) == "" || $k == 'page') ;
	}

}

app/Http/Controllers/Sadmin/MsgsController.php
<?php

namespace App\Http\Controllers\Sadmin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\GroupMsg ;
use App\Msg ;
use App\User ;

class MsgsController extends Controller
{
    public function index()
    {    	
    	return view("sadmin/msgs/index") ;
    }

    public function show(GroupMsg $group)
    {
    	$msgs = $group->msgs ;
        $oneSide = $group->from_user_id ;
    	return view("sadmin/msgs/show",compact("group","msgs","oneSide")) ;
    }

    public function create()
    {
    	$users = User::notAdmin()->get() ;
    	return view("sadmin.msgs.create",compact("users")) ;
    }

    public function store(Request $request)
    {
    	$this->validate($request , [
            "titlemsg" => "required",
            "contentmsg" => "required" ,
            "target" => "required|exists:users,id"
        ]) ;

        $group = GroupMsg::create([
            "to_user_id" => $request->target ,
            "title" => $request->titlemsg ,
            "from_user_id" => 0
        ]);

        Msg::create([
            "group_id" => $group->id ,
            "to_user_id" => $request->target ,
            "content" => $request->contentmsg ,
            "from_user_id" => 0
        ]);

        return back()->with([
            "success-message" => "تم ارسال الرسالة" ,
        ]) ;

    }

    public function newMsg(Request $request , GroupMsg $group)
    {
        $this->validate($request , [
            "contentmsg" => "required" ,            
        ]) ;
        
        $group->msgs()->create([
            "to_user_id" => ( $group->from_user_id == 0 ? $group->to_user_id : $group->from_user_id ) ,
            "content" => $request->contentmsg ,
            "from_user_id" => 0
        ]);

        return back()->with([
            "success-message" => "تم ارسال الرسالة" ,
        ]) ;
    }

}

resources/views/sadmin/admins/edit.blade.php
@extends("sadmin/layouts/app")

@section("title",$user->name)

@push("active-users")
active open 
@endpush

@push("active-users-1")
active 
@endpush

@push("scripts")
<script src="/sadminassets/js/jquery.datetimepicker.full.min.js"></script>
<script>
	jQuery.datetimepicker.setLocale('ar');
	jQuery('.date').datetimepicker({
		timepicker:false,
		lang:'ar',
		format: 'Y-m-d'
	});
</script>
@endpush

@push("styles")
	<link rel="stylesheet" href="/sadminassets/css/jquery.datetimepicker.css" />
@endpush



@section("content")
<!-- Personel informations  -->
<div class="portlet light bg-inverse">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-user"></i> {{$user->name}}
		</div>

		<form action="{{ route('sadmin.users.destroy',$user->id) }}" method="post" class="actions" >

			<a href="{{ route('sadmin.users.edit',$user->id) }}" class="btn btn-info btn-sm">
				<i class="fa fa-undo"></i> إلغاء
			</a>

			{{csrf_field()}}
			{{method_field('delete')}}
			<button type="submit" class="btn btn-danger btn-sm">
				<i class="fa fa-trash"></i> حذف
			</button>
		</form>
		
	</div>
	<div class="portlet-body flip-scroll" >
		<form action="{{ route('sadmin.users.update',$user->id) }}" method="post" enctype="multipart/form-data" >
			{{csrf_field()}}
			{{method_field('put')}}

			<div class="clearfix">
				@include("sadmin/layouts/msgs")
			</div>
			<div class="clearfix" >
				<!-- name -->

				<div class="col-xs-12 col-md-6 pull-right text-center">
					<img src="{{ $user->completAvatarUrl }}" class="avatar-user-in-sadminpage" >
				</div>
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>الاسم الثلاثي</label>
						<input type="text" class="form-control" value="{{ old('name') ?: $user->name }}" name="name" >
					</div>
				</div>
				<!-- birth day -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>تاريخ الميلاد</label>
						<input type="text" class="date form-control" value="{{ old('birthday') ?: $user->birthday }}" name="birthday" >                    
					</div>
				</div>
				<!-- email -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>البريد الإلكتروني</label>
						<input type="email" class="form-control" value="{{ old('email') ?: $user->email }}" name="email" >                    
					</div>
				</div>
				<!-- phone -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>رقم الهاتف</label>
						<input type="text" class="form-control" value="{{ old('phone') ?: $user->phone }}" name="phone" >                    
					</div>
				</div>
				<!-- city -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>المدينة</label>
						<input type="text" class="form-control" value="{{ old('city') ?: $user->city }}" name="city" >                    
					</div>
				</div>
				<!-- postal -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>صندوق البريد</label>
						<input type="text" class="form-control" value="{{ old('postal') ?: $user->postal }}" name="postal" >                    
					</div>
				</div>
				<!-- location -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>المنطقة</label>
						<input type="text" class="form-control" value="{{ old('location') ?: $user->location }}" name="location" >                    
					</div>
				</div>
				<!-- Neighborhood -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>الحي</label>
						<input type="text" class="form-control" value="{{ old('ngbh') ?: $user->ngbh }}" name="ngbh" >
					</div>
				</div>
				<!-- street -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>الشارع</label>
						<input type="text" class="form-control" value="{{ old('street') ?: $user->street }}" name="street" >                    
					</div>
				</div>
				@if($user->can("is-simpleuser"))
				<!-- designer -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>المصمم المتابع</label>
						<p>
							@if($user->follower)
							<a href="{{ route('sadmin.users.edit',$user->follower->id) }}">{{$user->follower->name}}</a>
							@else
							<span class="text-danger">لا يتابعه اي مصمم</span>
							@endif
						</p>
					</div>
				</div>
				<!-- Upadte designer -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>تعيين مصمم للمستخدم</label>
						<select name="follower_id" class="form-control" >
							<option selected value="">اختر مصممًا</option>
							@foreach($designers as $designer)
							<option {{ $user->follower_id == $designer->id ? 'selected' : '' }} value="{{ $designer->id }}">{{$designer->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				@endif
				<!-- img -->
				<div class="col-xs-12 col-md-6 pull-left">
					<div class="form-group">
						<label>الصورة الشخصية</label>
						<input type="file" name="avatar" >
					</div>
				</div>
				<div class="col-xs-12">
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-sm">
							<i class="fa fa-pencil"></i> حفظ
						</button>
					</div>
				</div>

			</div>

			<change-password />
		</form>
	</div>
</div>

<div class="clearfix">
	@include("sadmin/users/upgrade")
</div>
@endsection

resources/views/sadmin/admins/index.blade.php
@extends("sadmin/layouts/app")

@section("title","المدراء")

@push('active-admins-1')
active 
@endpush

@push('active-admins')
active open
@endpush

@section("content")

<div class="portlet light bg-inverse">
	<div class="portlet-title">
		<div class="caption font-purple uab">
			<i class="fa font-purple fa-user-circle-o"></i> كافة المدراء
		</div>
	</div>
	<div class="portlet-body flip-scroll">
	
		<div>
			@include("sadmin/layouts/msgs")
		</div>
		
		<table-designers json="admins" ></table-designers>
	</div>
</div>

@endsection